### ISSUE TITLE
"Remove Trailing Whitespace" should not be on by default

### ISSUE THREAD

**Issue by ceejayoz** [atom/whitespace#10]
Indented blank lines is a pretty common use case. Having them destructively removed by default is going to lead to a lot of confusion when users inadvertently commit massive whitespace changesets they didn't notice on saving to their Git repos.

**Comment by ghanique** [comment]
+1 for opt-in!
It's making lots of changes to files that make working with git pretty hard because I not only see the lines I changes, but all lines that are changed by atom.
Furthermore, for markdown there is reason to have two tailing white spaces.

**Comment by 50Wliu** [comment]
Again, it is easily opt-outable as described above.  For specific languages, you can also created scoped settings for them, also as described above.
I think by this point it's pretty clear that the Atom team will keep this setting on by default.  Perhaps though a notice can be added in Welcome.md @benogle?

**Comment by ghanique** [comment]
It's not easy. It took quite some googling to find this thread. But feel
free to keep it on by default, it's your project :) Now I know how to
disable it it isn't an issue anymore and overall I'm quite happy with the
Atom Editor.

(I'd like to be able to open log files with it, which are generally larger
than 2MB, but that's probably another thread :-) ).

**Comment by 50Wliu** [comment]
@ghanique yep, atom/atom#307.  Though if you don't need to edit those files, there's always the [view-tail-large-files](https://atom.io/packages/view-tail-large-files) package ;).

**Comment by pierreozoux** [comment]
<troll>
I keep thinking it's a conspiracy: this is the first time we see conflict of interests between atom development and Git hosting. This is obvious that GitHub will save Billions of dollar by not hosting these white spaces!
</troll>

**Comment by julienpa** [comment]
Very good point @pierreozoux ^^

**Comment by virtuald** [comment]
+1 for opt-in. Obviously it's not changing, but also got unexpectedly bit by this.

**Comment by virtuald** [comment]
+1 for opt-in. Obviously it's not changing, but also got unexpectedly bit by this.

Perhaps a better default is "if when loaded the file does not have extra whitespace, clean up extra whitespace the user adds. Otherwise don't remove extra whitespace". I would be ok with such a default.

**Comment by Nemesis-Xero** [comment]
One simple question: If "Remove Trailing Whitespace" is enabled by default for the purpose of keeping the code "clean" and removing "unnecessary" whitespace, then why is "Ensure Single Trailing Newline" also enabled by default? These two settings seem to be directly opposed to each other in terms of purpose.

**Comment by slang800** [comment]
@Nemesis-Xero - because non-empty files are supposed to end in a newline. All Unix tools expect this convention and work with it. For instance, when concatenating files with cat, a file terminated by newline will have a different effect than one without.

However, "Ensure Single Trailing Newline" will remove extraneous trailing newlines, so it also works on keeping your code clean, like "Remove Trailing Whitespace" does.

**Comment by gregmac** [comment]
+1 on opt-in. This is endlessly frustrating when working with source control. 

No offence, but dictating this type of thing is just as offensive as if I create a pull request for this project and change all your spaces to tabs (because "my editor automatically does that"), or changes your variables to `underscore_style` or `PascalCase` or any other thing that changes the style to my own preferences. 

It is not the place of the atom/whitespace plugin maintainers to dictate what "clean" code should be on any project that gets touched by the Atom editor. This is especially problematic since it's a "core" plugin enabled with the default install.

Generally speaking, code etiquette is to maintain the original style of the code. The defaults in this plugin completely break that, and that's unacceptable.

**Comment by ghanique** [comment]
@gregmac +1 That is exactly why it shouldn't be enabled by default: it is not the editor's place to dictate what my files should look like.

**Comment by slang800** [comment]
@ghanique - "dictate" is a very strong word to use when talking about defaults for settings that can be changed. If Atom wanted to dictate this choice to you, wouldn't it need to make the setting immutable?

I can understand why you might not think this is a good default, but I have yet to hear an argument showing that Atom is _forcing_ this upon you.

**Comment by joeosburn** [comment]
It's a very opinionated setting to have on by default. Certain settings dictate the specifics of how a file should be handled, such as whitespace settings, and many of us work in environments where we want and embrace those kinds of settings, but to have a "dictatorial" type setting on by default seems to be too much.

**Comment by virtuald** [comment]
@ghanique , @gregmac, @slang800, @50Wliu,   others -- what about the compromise that I mentioned? Namely this:

A better default is "if when loaded the file does not have extra whitespace, clean up extra whitespace the user adds. Otherwise don't remove extra whitespace".

Most people won't notice/care if new whitespace gets removed. The problem/ugly commits occur when old whitespace gets removed. This seems like a good compromise.

**Comment by 50Wliu** [comment]
*Ideally*, I think that the best way to handle this would be to ask the user on first install.

Your suggested compromise seems like a nice start though.

**Comment by ghanique** [comment]
@sean: yes, dictate is a strong word :-), but is conveys the emotion a
little. An editor should assist me, not make decisions for me. I feel like
this setting is crossing that border. And by doing so it's not assisting me
anymore but actively working against me (by making lots of changes to files
that I did not intended but showing up as changes in the VCS anyway).

When I mentioned that I thought it a weird decision to make this the
default behavior some time ago I couldn't really put in words why I
disagreed. @grecmac did a better job, which is why I gave his message a +1.

I accepted the work around and your decision to have it enabled by default
- it's your product :-). I would disable it. Only changing white space in
lines that I'm changing would probably also be acceptable, but I can
imagine that it's more work and not worth the effort. (And there is the
concern that it conflicts with some markdown dialects where two white
spaces at the end of the line have meaning).

Kind regards,

Guillaume

**Comment by paulcbetts** [comment]
I can't use Atom to work on any existing C# project because it ends up writing dozens of spurious changes into the file because of this. 

> A better default is "if when loaded the file does not have extra whitespace, clean up extra whitespace the user adds. Otherwise don't remove extra whitespace".

I think this is a compromise that would work really well.

**Comment by gregmac** [comment]
@50Wliu Asking on install would certainly be better (at least users would be aware), but I don't think it's possible to do and maintain a good user experience. 

How do you ask them and explain the implications in enough detail without being overwhelming or annoying?  Also what other issues exist that would want a similar dialog (tabs vs spaces, for example), and does this lead to a future where there are dozens of options to pick on startup?

**Comment by gregmac** [comment]
So just to be clear:

* People that want the setting on by default (4): **benogle mokkabonna slang800 50Wliu**
* People that expressed explicit support for opt-in (24): **ceejayoz pierreozoux clintharris Shnick martindale hbirch barbagallo myktra joeosburn pmarchezz stevennoyce ioquatix Frijol noseglid  ccoenen amcinnes bancal laike9m julienpa kangear chesleybrown ghanique virtuald gregmac** 

There were also a handful of others on this thread that didn't clearly say it should be changed, but did end up on this ticket for a reason. 

On the flip side, there are probably many people that either like the defaults or don't care and haven't found or commented on this thread, but I'd counter-argue that people that definitely want their editor to clean up other people's whitespace shouldn't have an issue with explicitly telling their editor that.

----

The argument "for" this (by @mokkabonna) is:

> The problem is having those trailing whitespace there in the first place. Best way to deal with this in a project is to run a strip whitespace script on all your files, then commit just that. Clean, simple, solves the problem for the future. Keep the option on by default.

However I'd also argue that this default *does not even accomplish this goal*!

The current behavior causes unexpected changes on every save. If this is the goal, a better behaviour would be to have a popup when you open a file that says: 

    There are extra whitespace characters in this file. If you want, they can be 
    removed, at which point you should commit to source control before making changes. 

                                      [Leave as-is]   [Never prompt me about this again]
                                [Remove whitespace]    [Always remove without asking me] 

Also to @50Wliu 's comment:

> Again, it is easily opt-outable as described above

I'd say it is actually *not* easy. 

Most new users will not be aware a "whitespace" package exists at all (I didn't until I found this ticket), let alone it has settings or default destructive behavior. So a new user has to go to settings, know to click on "packages" (not obvious), know to search for "whitespace" (not obvious) or scroll through all 72 core packages looking for *something* and take a guess it might be "whitespace" package (again, not obvious).

The setting is called "Remove trailing whitespace" which also doesn't really entirely convey what it's doing, as opposed to something like "Remove all trailing whitespace in file on save".

----

There may be better fixes for the root issue (like @virtuald's suggestion, or mine above) but until PR's exist, I'm strongly in support of merging in @ccoenen's #59.

**Comment by 50Wliu** [comment]
I should clarify-it is easily opt-outable if one is familiar with how Atom handles packages.  It *will* become easily opt-outable in all cases when package and core settings are unified.

I'd argue that "Remove trailing whitespace" is actually fairly accurate, since there is no way to actually do anything to a file without saving it, no?

**Comment by slang800** [comment]
> So just to be clear:
> -    People that want the setting on by default (4): [...]
> -    People that expressed explicit support for opt-in (24): [...]

This statistic is misleading because this thread is almost exclusively commented on by users who have noticed the behaviour, didn't like it, and didn't see the whitespace package. Thus, the people on this thread are not an accurate sample of the Atom userbase.

> I'd counter-argue that people that definitely want their editor to clean up other people's whitespace shouldn't have an issue with explicitly telling their editor that.

I'd counter-counter-argue that I would hate needing to go through some sort of configuration process (especially a popup). My editor should have reasonable defaults and I should only need to modify settings that I don't like. If there's a setting like whitespace that I don't care about, then I trust the Atom developers to have chosen the best default for me. I simply don't _want_ to have to decide on settings that I don't care about.

> However I'd also argue that this default does not even accomplish this goal!

I don't understand how that couldn't accomplish the goal. Unless users are deciding to avoid committing the whitespace removal, and letting those changes sit in their working directory forever. Elaborate?

> I'd say it is actually _not_ easy.

Moving the setting into a more visible place, or making the settings easier to search would be nice.

**Comment by thedaniel** [comment]
The solution most favored by the core team at this time is:

- Try to only strip whitespace from files that are clean when opened (i.e. detect whether it's going to make a huge diff on save and then don't do that)
- Improve settings-view to make this setting easier to discover.

The first item is more complicated and there's no estimate for when the core team will work on it, but PRs are very welcome. I expect the second item will be looked at in the next few months.

**Comment by gregmac** [comment]
@thedaniel I think that's a very reasonable approach.

> My editor should have reasonable defaults and I should only need to modify settings that I don't like.

I totally agree, and the argument I and many others are making is destructive changes are not a good default. Just because this happens to be one you like, you think it's good. 

If the default Atom behavior was to switch tabs to spaces, enforce Windows-style line ending (CRLF) and wrap all code at 80 columns, would that also be acceptable?

> I don't understand how that couldn't accomplish the goal. Unless users are deciding to avoid committing the whitespace removal, and letting those changes sit in their working directory forever. Elaborate?

You literally described what I was doing before I turned off the whitespace plugin completely. 

I open a file in a branch to make a single change, Atom creates a huge diff fixing up whitespace, so I ignore it and commit just the changes I want to make (because nobody will accept a PR with a bunch of style changes on top of a functional change). 

If I really wanted to fix the style and remove extra whitespace, I *could* then switch to master, create a new branch, fix the whitespace, commit and then submit a new PR. And I guess if I'm going to do that, the method using Atom is to open and then immediately save each file one-by-one? 

It does not accomplish the goal of fixing whitespace naturally, because developers that pay attention won't commit or accept unrelated changes. And if you do in fact want to cleanup the project and remove extra whitespace, it's a horribly inefficient way to do it.

**Comment by ccoenen** [comment]
@gregmac i could not have said it any more eloquently and clearly as you have. Thanks for these past three posts.

**Comment by paulcbetts** [comment]
> Try to only strip whitespace from files that are clean when opened (i.e. detect whether it's going to make a huge diff on save and then don't do that)

:+1: this works for me

**Comment by ccoenen** [comment]
"Only stripping on lines that i actually edited myself" AND "for fileformats where i know it's safe to do so" 
(combined as in `&&`) would also be acceptable in my opinion.

**Comment by ioquatix** [comment]
Destruction of whitespace entered by the user shouldn't be the default in any case.

> Try to only strip whitespace from files that are clean when opened (i.e. detect whether it's going to make a huge diff on save and then don't do that)

How is that going to work for a 500Mbyte database dump or log file?

**Comment by hbsdev** [comment]
I just commited a bunch of files that I edited with atom, only to find out that a lot of insignificant whitespace changes are no in the repository.

Very bad. At least it could have asked me. No more magic please.

**Comment by hbsdev** [comment]
it is not the editor's place to dictate what my files should look like.

**Comment by thomasjo** [comment]
> I just commited a bunch of files that I edited with atom, only to find out that a lot of insignificant whitespace changes are no in the repository.

While that's unfortunate, it's easily fixed. And for the future, you should pay more attention to what you're committing; it's good practice to have a quick glance at the diff of the stuff you are about to stage (or commit) — `git diff` is your friend.

---
With regards to the option itself being enabled by default, perhaps we should incorporate some info (with option to toggle the option) in the welcome guide? That way on first launch, new users would be aware of the feature, and can quickly disable it if they decide they don't like it? /cc @thedaniel

**Comment by pierreozoux** [comment]
Just by seeing the number of people that took time to come here to post something, I believe it is important :) Because, there is also the silent ones! (Ok, I posted more than once here :) )

**Comment by vinyar** [comment]
I definitely +1 on not making this a default, especially for files where spaces actually matter. This behavior should most definitely not be enforced in Markdown files.

Having spent nearly an hour trying to figure out why my Readme files look terrible, I finally arrived at this page.

**Comment by slang800** [comment]
> I definitely +1 on not making this a default, especially for files where spaces actually matter. This behavior should most definitely not be enforced in Markdown files.
> Having spent nearly an hour trying to figure out why my Readme files look terrible, I finally arrived at this page.

@vinyar: I find it hilarious that your comment moved from "nearly an hour" to "nearly two hours", and from "+1" to "+500" between edits.

As for the "hours of your work", it's probably a good idea to save more than once per "hours". Also, hitting `ctrl+z` will get you back to the point before the whitespace was stripped - it makes a history entry.

**Comment by vinyar** [comment]
@slang800 Simple - 'an hour' is a figure of speech, but the reality, is that between merging commits, fixing the files multiple times, googling, reading this thread, and filing the issue above it was around 4 hours of literally __wasted__ effort.  All in all, I am sorry that your sense of humor regarding usability of a tool leads you to find my wasted effort hilarious.

**Comment by afiune** [comment]
I just want to second what @vinyar is saying.. I tried Atom and after less than an "hour" I knew there was something wrong. Not nice you joke about other's people time. Be gently. Use https://github.com/SublimeText it is +500 better than this. 

Cheers.. :smile:

**Comment by ghanique** [comment]
SublimeText is probably better, but it's also $70. If your employer doesn't
want to spend that money than the Atom Editor with the white spacing turned
off makes your life considerably simpler than many other notepad-clones.

**Comment by thedaniel** [comment]
Let's not get too far from the topic of the issue. There are better places to discuss the relative merits of editors etc.

**Comment by sEver** [comment]
So I wanted whitespaces stripped from my *.jade files and I expected the default behavior to be "stripping whitespaces and adding newline at the end of file - enabled". 

I found this issue and I found the place to config the whitespace package. The thing is that apparently even though my whitespace package is ENABLED, it still doesn't work in Jade files, because of all the people here pushing against it and the https://github.com/atom/whitespace/pull/46 happening. 

Would be nice if that particular override happening for Jade files was included in the config file, or hinted at in the whitespace package configuration panel. 

Understandable that some people don't like their markup code destroyed, but whitespaces on a single line anywhere else is a bad idea and it's better to have one ugly commit than whitespaces all over the place. 

I do believe having clearing whitespaces on by default was a good call. Atom rocks.

**Comment by ghanique** [comment]
I do see what the problem is with a file where suddenly all the whitespaces are removed and the huge amount of merge conflicts that it creates in the VCS. 
I do not see the problem of a file with a lot of whitespaces that I don't see and that do not change the code. 

It's not like the whitespaces consume gigabytes of storage and increase the build time to several hours instead of seconds. Merge conflicts, however, can cost hours to resolve. And for what? To remove some characters I cannot see anyway?!?

In some markdown dialects two whitespaces at the end of the line DO have meaning. If they are removed the rendering changes. Great, now the tool DID change my source code... 

It would be great to have a menu item that I can click to remove all unnecessary whitespaces, but please do not make that many changes without asking me first!

The workaround it pretty simple: the first thing I do after installing the editor is disable the whitespace thing and then I'm fine. I still don't understand the reasoning, though, why people insist on having it enabled. But then again, who am i
?



—

**Comment by thomasjo** [comment]
I'm locking this since this will in all likelihood remain on by default, and it's relatively easy to disable;

![image](https://cloud.githubusercontent.com/assets/3622/6789873/e4439ec4-d1a3-11e4-9a0b-bdaaf097e727.png)

or by editing your `~/.atom/config.cson` file;
``` coffee
"*":
  whitespace:
    removeTrailingWhitespace: false
```

Note that this the feature can also be [disabled on a per-grammar basis](http://blog.atom.io/2014/10/31/language-scoped-config.html).
