### ISSUE TITLE
Follow .editorconfig settings

### ISSUE THREAD

**Issue by redbassett** [atom/whitespace#102]
Whitespace overrides the `trim_trailing_whitespace` setting by `.editorconfig` with the [editorconfig](https://atom.io/packages/editorconfig) package.

**Comment by lee-dohm** [comment]
Shouldn't this be on the [editorconfig repo](https://github.com/sindresorhus/atom-editorconfig)?

**Comment by redbassett** [comment]
I opened the issue here as I was under the impression that this package was overriding the other. Even if the `.editorconfig` file is set to allow whitespace (and therefore the `editorconfig` package isn't modifying whitespace), whitespace continues to be removed until I disable this package.

**Comment by lee-dohm** [comment]
Atom doesn't make a claim to support `.editorconfig` in any of its packages. Atom has its own configuration format.

Also, the editorconfig package in its [Supported Properties](https://github.com/sindresorhus/atom-editorconfig#supported-properties) doesn't state that it supports anything to do with whitespace trimming. So it would appear that the issue is that package having incomplete support for the feature you're expecting.

**Comment by redbassett** [comment]
https://github.com/sindresorhus/atom-editorconfig/issues/3

You'll notice that this behaviour by Sublime is why it isn't supported. Even if this package doesn't directly read `.editorconfig` settings, providing a way for the appropriate package to make the needed changes would be logical.

Categorize this instead as a request for per-buffer disabling of the whitespace trimming then.

**Comment by 50Wliu** [comment]
That's being tracked as a larger issue over at atom/atom#6589.

**Comment by redbassett** [comment]
While I still would love to see this as a compatability in the whitespace package, I'm glad there is consideration for including support in the core. Thanks for the link, @50Wliu!
