### ISSUE TITLE
Hotkeys to manually trigger trimming

### ISSUE THREAD

**Issue by ahnbizcad** [atom/whitespace#130]
Sometimes, You want more control over when / if it trims whitespace.

A convenient mode is to not have trim triggered on save, but to be able to trigger the trim when you want.

This is especially useful when working on different projects from different companies that have different preferences for creating noise in diffs.

**Comment by mnquintana** [comment]
You can do this now by assigning a custom keybinding to `whitespace:remove-trailing-whitespace`: http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings

I'm gonna close this out because we're trying to avoid adding more baked-in keyboard shortcuts, to leave them open for community package authors.
