### ISSUE TITLE
Do not strip whitespace from TSV files, even when enabled

### ISSUE THREAD

**Issue by skwerlman** [atom/whitespace#150]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When saving a TSV file, this plugin strips all trailing whitespace, breaking the file.

### Steps to Reproduce

1. Have a TSV file with one or more of the last columns empty
2. Save the file
3. Attempting to use the file will not work, because of missing columns

**Expected behavior:**
TSV files are excluded from whitespace trimming

**Actual behavior:**
TSV files are broken by this plugin

**Reproduces how often:**
Every time, as long as the TSV has an empty column at EOL

### Versions

```
Atom    : 1.15.0
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
```
```
apm  1.17.0
npm  4.4.4
node 7.7.3 x64
python 2.7.13
git 2.12.1
```

**Comment by 50Wliu** [comment]
> Electron: 1.4.15

Thanks for reaching out!

We've determined that you are using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).
