### ISSUE TITLE
Trailing spaces are removed even if the feature is disabled

### ISSUE THREAD

**Issue by pmilx** [atom/whitespace#152]
### Description

Trailing spaces are removed even if the feature is disabled or if the whole core package 'whitespace' is disabled. 

### Steps to Reproduce

1. Default behavior (Atom version 1.16.0 x64) - core package 'whitespace' is present by default.
2. Happening in ES6 template string:

For example:

const example = `
  sample text
`;

When saved all trailing spaces after 'sample text' are removed.

**Expected behavior:** Trailing spaces are not automatically removed if the features is disabled (or if package 'whitespace' is disabled).

**Actual behavior:** Trailing whitespaces are always removed when file is saved.

**Reproduces how often:** Everytime.

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Win 10

### Additional Information

N/A

**Comment by 50Wliu** [comment]
Does this happen in safe mode?

**Comment by pmilx** [comment]
Hi,

No it doesn’t happen in safe mode…

Thanks for your support!

Petr

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
