### ISSUE TITLE
Whitespace and Editorconfig plugins conflict

### ISSUE THREAD

**Issue by chimit** [atom/whitespace#188]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the Whitespace and Editorconfig plugins are enabled and `.editorconfig` file has `insert_final_newline ` and `trim_trailing_whitespace` parameters a wargning is displayed:

![image](https://user-images.githubusercontent.com/839349/58688640-9c892c00-83b7-11e9-976d-e0512b424e79.png)

> whitespace: It is possible that the "whitespace"-package prevents the following properties from working reliably: insert_final_newline, trim_trailing_whitespace. You may try reconfiguring or disabling the "whitespace"-package to solve regarding issues.

I can disable the Whitespace plugin but I still need it in projects which don't have `.editoconfig`. Is it possible to automatically deactivate the Whitespace plugin if Editorconfig is active the for current file? So Editorconfig just override the default (Whitespace) behavior.

### Steps to Reproduce

1. Use editorconfig plugin
2. Enable Whitespace plugin

**Expected behavior:** No warning.
a) If Editorconfig is set up: Atom follows Editorconfig settings
b) If Editorconfig isn't setup: Atom follows Whitespace settings

**Actual behavior:** Warning

**Reproduces how often:** Always

### Versions

Atom 1.37.0
Whitespace: 0.37.7
Editorconfig: 2.4.0

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [editorconfig](https://atom.io/packages/editorconfig) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
