### ISSUE TITLE
Converting a whole document to tabs/spaces doesn't change indentation settings for the document

### ISSUE THREAD

**Issue by DaanDD** [atom/whitespace#70]
Whenever I convert the whitespace in a full document from tabs to spaces, Atom will still use tabs on newlines. To make it use spaces I always have to close and reopen the file.

**Comment by shawninder** [comment]
I get this too. Quite annoying and probably a simple fix...

**Comment by dylanjameswagner** [comment]
I think this may be related to the Tab Type setting in Settings. The auto detection is at the time the file is opened and doesn't change just because you've converted the whitespace. I've been using [Tab Control](https://atom.io/packages/tab-control) as a secondary step to change the documents tab detection.
