### ISSUE TITLE
atom/Whitespace package eat random characters on save !

### ISSUE THREAD

**Issue by benogle** [atom/whitespace#99]
_From @jeancroy on November 4, 2015 18:35_

Step 1: atom --safe
Step 2: Open http://gundvang.dk/atom/fonts.js
Step 3: Save As `font2.js`
Step 4: Notice the missing `i`of `if` at line 22 and various missing character ( for example `$('.expanded')` at line 217 miss the `x`)
Step 5: Undo (file is ok)
Step 6: Disable package whitespace
Step 7: Save As `font3.js` (file is ok)
Step 8: Enable package whitespace
Step 9: Save As `font4.js`
Step 10: See the file mangled again (but in my case different mangle !)

[issue on discuss](https://discuss.atom.io/t/saving-js-and-scss-deletes-random-letters/20431/18)

![img1](https://i.gyazo.com/e676b79b43c92cf3944723ef40d7651f.png)

![img2](https://i.gyazo.com/888980d8af99ce4e75b07d47fd30c444.png)

_Copied from original issue: atom/atom#9438_

**Comment by benogle** [comment]
Thanks for the detailed repro steps.

**Comment by jeancroy** [comment]
Additional information: file that cause this use a mix of tab and space.
Reformatting that file to use only space prevent this error.

https://gist.github.com/jeancroy/b9c6ee3986160c88b2eb

**Comment by bxt** [comment]
@jeancroy I think I have found a file without tabs that triggers this bug: https://gist.githubusercontent.com/bxt/addc4eab08cdceb274d1/raw/0a4d5951cf7e986525e6c1735411855ff11fa223/main.js
I stored the file before and after saving in [a gist](https://gist.github.com/bxt/addc4eab08cdceb274d1), you can see the diff here: 
https://gist.github.com/bxt/addc4eab08cdceb274d1/revisions

**Comment by jeancroy** [comment]
Thank you.

**The first line indentation is messing with whitespace plugin, causing character deletions**

Step 1 : Open @bxt [main.js](https://gist.githubusercontent.com/bxt/addc4eab08cdceb274d1/raw/0a4d5951cf7e986525e6c1735411855ff11fa223/main.js)

Step 2: Save As main2.js

Step 3: Reopen main.js, see change
```
for example line 139:   $(window).on('resize',function(){
becomes line 136:       $(window).on('resiz,function(){
``` 
Step 4: Show whitespace, see main.js has no mixed indentation as first case
            BUT first line is indented with a single space.

Step 5: Delete that single whitespace. Save as main3.js

Step 6: reopen main.js, see that no random character deletion occured in main3.js.

---

Step5 alt: instead of deleting whitespace, insert a newline before it, so single whitespace is now on line 2. save as main4.js

Step6 alt: See that this also prevent random character deletion from occuring !

**Comment by jeancroy** [comment]
I tried to reproduce this on 1.8.0 beta 3.
- above font.js is no longer available.
- main.js don't trigger this.

Close this maybe ?
